spring:
  profiles.active: production

---


info:
  app:
    name: routes-optimizer-service
    description: Provides Optimized routes
    version: 1.0.0
    mode: default

endpoints:
  info:
    enabled: true
    sensitive: false

  health:
    sensitive: false
    
  metrics:
    sensitive: false

server:
    port:     9405

spring:
    profiles: production
    application:
        name: routes-optimizer-service 

zuul-edge-router:
    ribbon:
        ReadTimeout:    10000 
        ConnectTimeout: 10000
        NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.WeightedResponseTimeRule        

eureka:
    client:
        serviceUrl:
            defaultZone:    http://eureka-server:8761/eureka
        healthcheck:
            enabled: true
        instance:
            leaseRenewalIntervalInSeconds: 15
            preferIpAddress:  true
     